version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graph-rag
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - graph-rag-network

  app:
    build: .
    container_name: graph-rag-app
    restart: unless-stopped
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
      - TOKENIZERS_PARALLELISM=false
      - TF_CPP_MIN_LOG_LEVEL=3
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - graph-rag-network
    command: tail -f /dev/null # Keep container running

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:


networks:
  graph-rag-network:
    driver: bridge
